(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> contains() takes at least 3 arguments (4 given)"
p3
sS'layer'
p4
S'C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\applications\\rentapp\\controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 09F6AB60, file "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\applications\\rentapp\\controllers/default.py", line 1>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\applications\\rentapp\\controllers/default.py", line 53, in <module>\n  File "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\gluon\\globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\applications\\rentapp\\controllers/default.py", line 47, in searchresult\n    uploads=db(title_query).select()\n  File "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\gluon\\packages\\dal\\pydal\\objects.py", line 2250, in select\n    return adapter.select(self.query, fields, attributes)\n  File "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\sqlite.py", line 82, in select\n    return super(SQLite, self).select(query, fields, attributes)\n  File "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 757, in select\n    colnames, sql = self._select_wcols(query, fields, **attributes)\n  File "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 672, in _select_wcols\n    query = self.expand(query, query_env=query_env)\n  File "C:\\Users\\Ebenezer Appiah\\Desktop\\software\\windows\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 436, in _expand\n    rv = op(first, **optional_args)\nTypeError: contains() takes at least 3 arguments (4 given)\n'
p11
s.